# Generated by Django 4.0.2 on 2022-10-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('hdd', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('STARTED', 'Started'), ('BLOCKED', 'Blocked'), ('STOPPED', 'Stopped')], max_length=15)),
            ],
        ),
    ]
